default_stages: [commit]
repos:
  - repo: local
    hooks:
      - id: format-lint
        name: Run formatters and linters
        language: system
        entry: poetry run task
        args: ["lint"]
        always_run: true
        pass_filenames: false
      - id: test
        name: Run all tests for continuous integration
        language: system
        entry: poetry run task
        args: ["test_ci"]
        always_run: true
        pass_filenames: false