repos:
-   repo: https://github.com/ambv/black
    rev: 22.6.0
    hooks: 
    -   id: black
        language_version: python3.10
        stages: [commit]
-   repo: https://github.com/pycqa/isort
    rev: 5.10.1
    hooks:
      - id: isort
        name: isort (python)
-   repo: https://gitlab.com/pycqa/flake8
    rev: 5.0.4
    hooks:
    -   id: flake8
        stages: [commit]
-   repo: local
    hooks:
    -   id: pytest-api
        name: test api
        language: system
        entry: bash -c '.venv/bin/pytest -v -s src/api/tests'
        always_run: true
        pass_filenames: false
        stages: [commit]
    -   id: pytest-pipeline
        name: test data pipeline
        language: system
        entry: bash -c '.venv/bin/pytest -v -s src/pipeline/stages/tests'
        always_run: true
        pass_filenames: false
        stages: [commit]
-   repo: local
    hooks:
    -   id: requirements
        name: update requirements file
        language: system
        entry: bash -c '.venv/bin/pip freeze > requirements.txt && git add requirements.txt'
        pass_filenames: false
        stages: [commit]