repos:
-   repo: https://github.com/pycqa/isort
    rev: 5.10.1
    hooks:
      - id: isort
        name: isort (sorter)
        stages: [commit]

-   repo: https://github.com/ambv/black
    rev: 22.6.0
    hooks: 
    -   id: black
        name: black (formatter)
        stages: [commit]

-   repo: https://gitlab.com/pycqa/flake8
    rev: 5.0.4
    hooks:
    -   id: flake8
        name: flake8 (linter)
        stages: [commit]

-   repo: local
    hooks:
    -   id: pytest
        name: pytest (tests)
        language: system
        entry: bash -c '.venv/bin/pytest -v -s src/fishermanpy/tests/'
        always_run: true
        pass_filenames: false
        stages: [commit]

-   repo: local
    hooks:
    -   id: requirements
        name: update and git add requirements file
        language: system
        entry: bash -c '.venv/bin/pip freeze > requirements.txt && git add requirements.txt'
        pass_filenames: false
        stages: [commit]